import { Conversation } from "../util/Conversation.js"
import type { Message } from "../util/Conversation.js"


/**
 * Abstract base class for components that read conversation history and
 * produce a new message.
 *
 * A client owns or shares a {@link Conversation} instance and may use that
 * conversation to call an AI model, transform the latest message, transcribe
 * audio, or perform another message-processing operation.
 *
 * Concrete subclasses must implement {@link getReply}.
 */
export abstract class Client
{
     /**
     * Display name of the person on the other side of the conversation.
     *
     * This name is included in the generated system prompt so that subclasses
     * can provide the model with basic information about the user or remote
     * participant.
     */
    private readonly oppositeName: string

    /**
     * Conversation history used by this client.
     *
     * The conversation may be created automatically by the constructor or
     * supplied externally so that multiple clients can operate on the same
     * conversation state.
     */
    private readonly prompt: string

    /**
     * Conversation history used by this client.
     *
     * The conversation may be created automatically by the constructor or
     * supplied externally so that multiple clients can operate on the same
     * conversation state.
     */
    private readonly conversation: Conversation


    /**
     * Creates a new client.
     *
     * @param oppositeName      Human-readable name of the person on the other side of the conversation.
     *                          The name is included in the system prompt returned by
     *                          {@link getPrompt}. It is also passed to the default
     *                          {@link Conversation} constructor when no conversation is provided.
     *
     * @param prompt            Optional client-specific system prompt text.
     *                          The value defaults to an empty string. Empty or whitespace-only prompt
     *                          text is omitted from the final prompt generated by {@link getPrompt}.
     *
     * @param conversation      Conversation history used by this client.
     *                          The value defaults to a new {@link Conversation} created with
     *                          `oppositeName`. An existing conversation may be supplied when several
     *                          clients need to share and modify the same message history.
     */
    constructor(oppositeName: string, prompt: string = "", conversation: Conversation = new Conversation(oppositeName))
    {
        this.oppositeName = oppositeName
        this.prompt = prompt
        this.conversation = conversation
    }


    /**
     * Produces the next message based on the current conversation state.
     *
     * Concrete subclasses may implement this operation by calling a language
     * model, transcribing audio, transforming multimodal data, or performing
     * another conversation-processing task.
     *
     * This method does not define whether the returned message is
     * automatically added to the conversation. That behavior is determined
     * by the caller or concrete subclass.
     *
     * @returns                 A promise resolving to:
     *                          - A generated or transformed {@link Message} when processing succeeds.
     *                          - `null` when the client cannot produce a message.
     *
     * @throws
     * May reject when the underlying model request, transformation, network
     * operation, or other client-specific processing fails.
     */
    abstract getReply(): Promise<Message | null>


    /**
     * Builds the system prompt fragment shared by model-based clients.
     *
     * The resulting prompt contains:
     *
     * 1. A sentence identifying the person on the other side.
     * 2. The optional client-specific prompt supplied to the constructor.
     *
     * Empty or whitespace-only parts are removed before the remaining parts
     * are joined with a single space.
     *
     * @returns                 A system prompt string containing the opposite participant's name and,
     *                          when present, the client-specific prompt text.
     */
    protected getPrompt(): string
    {
        return [
            `The person on the other side is named: ${this.oppositeName}.`,
            this.prompt,
        ].filter(part => part.trim().length > 0).join(" ")
    }


    /**
     * Returns the conversation used by this client.
     *
     * The returned object is the actual shared {@link Conversation} instance,
     * not a copy. Changes made through the returned object are therefore
     * visible to this client and to every other client sharing the same
     * conversation.
     *
     * @returns                 The conversation instance owned or shared by this client.
     */
    getConversation(): Conversation
    {
        return this.conversation
    }


    /**
     * Appends a system message to the conversation.
     *
     * This method assumes that the supplied message already has the correct
     * system role. The method itself does not validate or modify the message
     * role.
     *
     * @param message           System-role message to append to the end of the conversation history.
     *
     * @returns                 The current client instance, allowing chained method calls.
     *
     * @example
     * ```ts
     * client
     *     .addSystemMessage(systemMessage)
     *     .addUserMessage(userMessage)
     * ```
     */
    addSystemMessage(message: Message): Client
    {
        this.conversation.addMessage(message)
        return this
    }


    /**
     * Appends a user message to the conversation.
     *
     * This method assumes that the supplied message already has the correct
     * user role. The method itself does not validate or modify the message
     * role.
     *
     * @param message           User-role message to append to the end of the conversation history.
     *
     * @returns                 The current client instance, allowing chained method calls.
     */
    addUserMessage(message: Message): Client
    {
        this.conversation.addMessage(message)
        return this
    }


    /**
     * Appends an assistant message to the conversation.
     *
     * This method assumes that the supplied message already has the correct
     * assistant role. The method itself does not validate or modify the
     * message role.
     *
     * @param message
     * Assistant-role message to append to the end of the conversation history.
     *
     * @returns
     * The current client instance, allowing chained method calls.
     */
    addAssistantMessage(message: Message): Client
    {
        this.conversation.addMessage(message)
        return this
    }


    /**
     * Removes the latest conversation message when it is the expected object.
     *
     * This method is commonly used to roll back a temporary message after a
     * failed model request or unsuccessful processing attempt.
     *
     * The removal succeeds only when `message` is the exact message object
     * currently stored at the end of the conversation.
     *
     * @param message           Message expected to be the latest entry in the conversation.
     *
     * @returns                 `true` when the supplied message was the latest conversation entry and
     *                          was removed successfully.
     *                          Returns `false` when the conversation is empty, when another message is
     *                          currently last, or when the conversation rejects the removal.
     */
    removeLastMessage(message: Message): boolean
    {
        return this.conversation.removeLastMessage(message)
    }
}
