import process from "node:process"

import { Conversation, Message, TextData } from "../util/Conversation.js"
import { ROLE_ASSISTANT, ROLE_SYSTEM, ROLES } from "../util/Misc.js"
import { Client } from "./Client.js"

import type { Data } from "../util/Conversation.js"


/**
 * Configuration options for {@link OllamaClient}.
 */
type OllamaClientOptions = {
    
    /**
     * Base URL of the Ollama HTTP API.
     *
     * When omitted, the client first checks the `OLLAMA_BASE_URL`
     * environment variable and then falls back to {@link DEFAULT_BASE_URL}.
     *
     * @example
     * ```ts
     * "http://127.0.0.1:11434"
     * ```
     */
    baseUrl?: string

    /**
     * Name of the Ollama model used for chat completion requests.
     *
     * When omitted, the client first checks the `OLLAMA_MODEL`
     * environment variable and then falls back to {@link DEFAULT_MODEL}.
     *
     * @example
     * ```ts
     * "qwen3.5:4b"
     * ```
     */
    model?: string

    /**
     * Additional system prompt text for this client.
     *
     * The base {@link Client} combines this value with the generated context
     * describing the person on the other side of the conversation.
     */
    prompt?: string

    /**
     * Optional model sampling temperature.
     *
     * Lower values generally produce more deterministic responses, while
     * higher values generally increase variation.
     *
     * When omitted, no temperature override is sent and Ollama uses the
     * model's configured default.
     */
    temperature?: number

    /**
     * Existing conversation to use for request history.
     *
     * Supplying this option allows multiple clients to share the exact same
     * {@link Conversation} instance.
     *
     * When omitted, the base {@link Client} creates a new conversation.
     */
    conversation?: Conversation
}


/**
 * Default base URL for a locally running Ollama server.
 */
const DEFAULT_BASE_URL = "http://127.0.0.1:11434"

/**
 * Default Ollama model used when neither the constructor options nor the
 * environment variables provide a model name.
 */
const DEFAULT_MODEL = "qwen3.5:4b"


/**
 * Client that sends conversation history to Ollama's `/api/chat` endpoint and
 * converts the returned assistant text into the project's internal
 * {@link Message} representation.
 *
 * This implementation currently sends text-only messages. Images, videos,
 * audio, and files stored in the internal conversation are ignored by
 * {@link converter}.
 */
export class OllamaClient extends Client
{

    /**
     * Base URL used for Ollama HTTP requests.
     *
     * The final chat endpoint is constructed by appending `/api/chat`.
     */
    private readonly baseUrl: string

    /**
     * Ollama model name included in every chat request.
     */
    private readonly model: string

    /**
     * Optional sampling temperature included in the Ollama request options.
     *
     * A value of `undefined` means that the request does not override the
     * model's default temperature.
     */
    private readonly temperature: number | undefined

    
    /**
     * Creates an Ollama chat client.
     *
     * Configuration values are resolved using the following precedence:
     *
     * 1. Explicit values supplied through `options`.
     * 2. Supported environment variables.
     * 3. Built-in default values.
     *
     * @param oppositeName      Human-readable name of the person on the other side of the conversation.
     *
     *                          The name is passed to the base {@link Client} and included in the system
     *                          prompt generated by {@link Client.getPrompt}.
     *
     * @param options           Optional Ollama connection, model, prompt, sampling, and conversation
     *                          configuration.
     *
     * @param options.baseUrl   Base URL of the Ollama HTTP server.
     *
     *                          When omitted, `process.env.OLLAMA_BASE_URL` is used when available,
     *                          followed by {@link DEFAULT_BASE_URL}.
     *
     * @param options.model     Ollama model name used for chat requests.
     *
     *                          When omitted, `process.env.OLLAMA_MODEL` is used when available,
     *                          followed by {@link DEFAULT_MODEL}.
     *
     * @param options.prompt    Additional client-specific system prompt text.
     *
     * @param options.temperature   Optional sampling temperature sent through Ollama's `options` object.
     *
     * @param options.conversation  Existing conversation instance to share with this client.
     */
    constructor(oppositeName: string, options: OllamaClientOptions = {})
    {
        super(oppositeName, options.prompt, options.conversation)
        this.baseUrl = options.baseUrl ?? process.env.OLLAMA_BASE_URL ?? DEFAULT_BASE_URL
        this.model = options.model ?? process.env.OLLAMA_MODEL ?? DEFAULT_MODEL
        this.temperature = options.temperature
    }


    /**
     * Sends the current conversation to Ollama and returns the generated
     * assistant message.
     *
     * Processing sequence:
     *
     * 1. Converts the internal conversation into Ollama message objects.
     * 2. Builds the `/api/chat` request body.
     * 3. Sends a non-streaming HTTP request.
     * 4. Reads the assistant text from the JSON response.
     * 5. Removes any embedded model thinking block.
     * 6. Wraps the remaining text in an assistant-role {@link Message}.
     *
     * @returns                 A promise resolving to:
     *
     *                          - An assistant-role {@link Message} when Ollama returns non-empty text.
     *                          - `null` when the HTTP response status is unsuccessful.
     *                          - `null` when the response contains no usable assistant text.
     *
     * @throws                  Rejects when the network request fails, response JSON cannot be parsed,
     *                          or another unexpected error occurs.
     */
    override async getReply(): Promise<Message | null>
    {
        const messages = this.toOllamaMessages(this.getConversation())

        const response = await fetch(`${this.baseUrl}/api/chat`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(this.createRequestBody(messages)),
        })

        if (!response.ok)
            return null

        const data = await response.json() as { message?: { content?: string } }
        const content = this.cleanReply(data.message?.content ?? "")

        if (content.length === 0)
            return null

        return new Message(ROLE_ASSISTANT).addData(new TextData(content))
    }


    /**
     * Builds the JSON request body expected by Ollama's `/api/chat` endpoint.
     *
     * The request disables token streaming and model thinking output.
     *
     * The `options` object is included only when a temperature value was
     * explicitly configured.
     *
     * @param messages          Ordered Ollama-compatible message list generated by
     *                          {@link toOllamaMessages}.
     *
     *                          Each message contains:
     *                          - `role`: A supported system, user, or assistant role.
     *                          - `content`: The text content sent to the model.
     *
     * @returns                 An object suitable for JSON serialization and submission to Ollama's
     *                          `/api/chat` endpoint.
     */
    private createRequestBody(messages: ReturnType<OllamaClient["toOllamaMessages"]>)
    {
        return {
            model: this.model,
            messages,
            stream: false,
            think: false,
            ...(this.temperature === undefined ? {} : { options: { temperature: this.temperature } }),
        }
    }


    /**
     * Converts an internal conversation into Ollama-compatible chat messages.
     *
     * A system message generated by {@link Client.getPrompt} is always inserted
     * first. Valid non-empty conversation messages are appended afterward in
     * their original order.
     *
     * Because the configured model is treated as text-only, only text data is
     * extracted from each internal message.
     *
     * @param conversation      Internal conversation whose messages should be converted.
     *
     * @returns                 An ordered array of Ollama chat message objects.
     *
     *                          Every returned object contains:
     *                          - `role`: A role supported by this project.
     *                          - `content`: Non-empty text content.
     */
    private toOllamaMessages(conversation: Conversation)
    {
        const messages = [
            {
                role: ROLE_SYSTEM,
                content: this.getPrompt(),
            },
        ]

        for (const message of conversation.serialize().content)
        {
            const content: string = this.converter(message.content).trim()

            if (!this.isRole(message.role) || content.length === 0)
                continue

            messages.push({
                role: message.role,
                content,
            })
        }

        return messages
    }


    /**
     * Extracts textual content from an internal message.
     *
     * Multiple text items are joined with newline characters in their original
     * order. Non-text items are ignored because this client currently assumes
     * that the configured Ollama model accepts text input only.
     *
     * @param content           Ordered list of internal data items belonging to one conversation
     *                          message.
     *
     *                          Supported data variants include:
     *                          - `"text"`
     *                          - `"image_url"`
     *                          - `"video_url"`
     *                          - `"input_audio"`
     *                          - `"input_file"`
     *
     * @returns                 A string containing all text items joined by newline characters.
     *                          Returns an empty string when the message contains no text items.
     */
    private converter(content: Data[]): string
    {
        const texts: string[] = []

        for (const data of content)
        {
            switch (data.type)
            {
                case "text":
                {
                    texts.push(data.text)
                    break
                }

                case "image_url":
                case "video_url":
                case "input_audio":
                case "input_file":
                    break
            }
        }

        return texts.join("\n")
    }


    /**
     * Checks whether a value is one of the conversation roles supported by
     * this project.
     *
     * This method is also a TypeScript type guard. After it returns `true`,
     * TypeScript narrows `value` to one of the entries in {@link ROLES}.
     *
     * @param value             Unknown value to validate as a conversation role.
     *
     * @returns                 `true` when `value` is a string contained in {@link ROLES}; otherwise
     *                          `false`.
     */
    private isRole(value: unknown): value is typeof ROLES[number]
    {
        return typeof value === "string" && (ROLES as readonly string[]).includes(value)
    }


    /**
     * Removes model thinking blocks from an assistant reply.
     *
     * Every case-insensitive `<think>...</think>` block is removed, including
     * content spanning multiple lines. Leading and trailing whitespace is then
     * trimmed from the remaining reply.
     *
     * @param reply             Raw assistant response text returned by Ollama.
     *
     * @returns                 Cleaned assistant text without thinking blocks or surrounding
     *                          whitespace.
     *
     *                          Returns an empty string when the reply contains only whitespace or
     *                          thinking content.
     */
    private cleanReply(reply: string): string
    {
        return reply
            .replace(/<think>[\s\S]*?<\/think>/gi, "")
            .trim()
    }
}
